import CloudKit
import CoreData
import SwiftData
import XCTest
import SwiftUI
import UIKit
@testable import MonthlyMoney

@MainActor
final class MonthlyMoneyTests: XCTestCase {
    private static var retainedHostedTestObjects: [AnyObject] = []

    override func setUpWithError() throws {
        print("TEST START: \(name) @ \(Date())")
    }

    override func tearDownWithError() throws {
        print("TEST END: \(name) @ \(Date())")
    }

    private func nextMonth(after month: YearMonth) -> YearMonth {
        var year = month.year
        var value = month.month + 1
        if value > 12 {
            value = 1
            year += 1
        }
        return YearMonth(year: year, month: value)
    }

    func testBootstrapCreatesLocalBudgetAndLoadsCurrentMonth() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()

        XCTAssertEqual(try repository.activeBudget()?.sharingState, .local)
        XCTAssertEqual(try repository.activeBudget()?.usesSeparateAccountForDailyBudget, false)
        XCTAssertTrue(state.monthItems.isEmpty)
        XCTAssertEqual(state.primaryBankBalance, 0)
        XCTAssertTrue(state.canNavigateToNextMonth)
        XCTAssertEqual(state.primaryBankName, "Nationwide")
    }

    func testCanNavigateToNextMonthWhenCurrentMonthIsEmpty() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()

        XCTAssertFalse(state.isSelectedMonthInFuture)
        XCTAssertTrue(state.monthItems.isEmpty)
        XCTAssertTrue(state.canNavigateToNextMonth)
    }

    func testCannotNavigateToNextMonthWhenFutureMonthIsEmpty() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        state.selectedMonth = nextMonth(after: state.selectedMonth)
        try state.refresh()

        XCTAssertTrue(state.isSelectedMonthInFuture)
        XCTAssertTrue(state.monthItems.isEmpty)
        XCTAssertFalse(state.canNavigateToNextMonth)
    }

    func testDailyBudgetAccountSettingPersistsOnActiveBudget() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        XCTAssertFalse(state.usesSeparateAccountForDailyBudget)

        state.usesSeparateAccountForDailyBudget = true

        XCTAssertTrue(state.usesSeparateAccountForDailyBudget)
        XCTAssertEqual(try repository.activeBudget()?.usesSeparateAccountForDailyBudget, true)
    }

    func testDailyBudgetInputsPersistOnActiveBudget() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()

        XCTAssertEqual(state.dailyBudgetAmount, 0)
        XCTAssertEqual(state.dailyBudgetPaydayDay, 1)

        state.dailyBudgetAmount = 1550
        state.dailyBudgetPaydayDay = 28

        XCTAssertEqual(state.dailyBudgetAmount, 1550)
        XCTAssertEqual(state.dailyBudgetPaydayDay, 28)
        XCTAssertEqual(try repository.activeBudget()?.dailyBudgetAmount, 1550)
        XCTAssertEqual(try repository.activeBudget()?.dailyBudgetPaydayDay, 28)
    }

    func testBudgetDefaultsWheelOfMoneySavingsGenerationToOff() {
        let budget = Budget(name: "Household", ownerParticipantID: "rog")

        XCTAssertFalse(budget.autoGenerateWoMSavingsEveryMonth)
    }

    func testWheelOfMoneyItemStoresCoreFields() {
        let budgetID = UUID()
        let item = WheelOfMoneyItem(
            budgetID: budgetID,
            title: "Christmas",
            amount: 1000,
            month: 12,
            isPaid: false,
            notes: "Presents",
            isAutoGeneratedSavingsEntry: true
        )

        XCTAssertEqual(item.budgetID, budgetID)
        XCTAssertEqual(item.title, "Christmas")
        XCTAssertEqual(item.amount, 1000)
        XCTAssertEqual(item.month, 12)
        XCTAssertFalse(item.isPaid)
        XCTAssertEqual(item.notes, "Presents")
        XCTAssertTrue(item.isAutoGeneratedSavingsEntry)
    }

    func testBootstrapLeavesWheelOfMoneyEmpty() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()

        XCTAssertTrue(state.wheelOfMoneyItems.isEmpty)
    }

    func testWheelOfMoneyMetricsAndPendingFilter() {
        let budgetID = UUID()
        let items = [
            WheelOfMoneyItem(budgetID: budgetID, title: "Car insurance", amount: 900, month: WheelOfMoneyMonth.march.rawValue, isPaid: false),
            WheelOfMoneyItem(budgetID: budgetID, title: "Christmas", amount: 1000, month: WheelOfMoneyMonth.december.rawValue, isPaid: false),
            WheelOfMoneyItem(budgetID: budgetID, title: "J Birthday", amount: 150, month: WheelOfMoneyMonth.may.rawValue, isPaid: true)
        ]

        let metrics = WheelOfMoneyCalculator.metrics(items: items, currentMonth: 3)

        XCTAssertEqual(metrics.annualTotal, 2050)
        XCTAssertEqual(metrics.monthlyAverage, Decimal(2050) / Decimal(12))
        XCTAssertEqual(metrics.pendingTotal, 1900)
        XCTAssertEqual(metrics.remainingAverage, Decimal(1900) / Decimal(10))
        XCTAssertTrue(metrics.remainingAverageExceedsMonthlyAverage)
        XCTAssertEqual(
            WheelOfMoneyFilterRules.filteredItems(items, for: .pending).map(\.title).sorted(),
            ["Car insurance", "Christmas"]
        )
    }

    func testEnablingWheelOfMoneySavingsGenerationDoesNotCreateEntriesImmediately() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        XCTAssertFalse(state.autoGenerateWoMSavingsEveryMonth)

        try repository.createWheelOfMoneyItem(
            WheelOfMoneyItem(
                budgetID: UUID(),
                title: "Car insurance",
                amount: 900,
                month: WheelOfMoneyMonth.march.rawValue,
                isPaid: false
            )
        )
        try state.refresh()

        state.autoGenerateWoMSavingsEveryMonth = true
        XCTAssertFalse(
            try repository.plannedItems(for: state.selectedMonth).contains(where: { $0.label == "WoM savings" })
        )
    }

    func testPopulatingMonthCreatesWheelOfMoneySavingsDebitWhenEnabled() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        try repository.createWheelOfMoneyItem(
            WheelOfMoneyItem(
                budgetID: UUID(),
                title: "Car insurance",
                amount: 900,
                month: WheelOfMoneyMonth.march.rawValue,
                isPaid: false
            )
        )
        state.autoGenerateWoMSavingsEveryMonth = true
        let targetMonth = nextMonth(after: state.selectedMonth)
        let accountID = try XCTUnwrap(try repository.accounts().first).id
        try repository.createPlannedItem(
            PlannedItem(
                accountID: accountID,
                monthKey: state.selectedMonth,
                type: .fixedDebit,
                label: "Rent",
                amount: 1200,
                dueDay: 1,
                isPaid: false
            )
        )
        state.selectedMonth = targetMonth
        try state.refresh()

        state.populateSelectedMonthFromPrevious()

        let savingsDebit = try XCTUnwrap(
            try repository.plannedItems(for: targetMonth).first(where: { $0.label == "WoM savings" })
        )
        let expectedAmount = WheelOfMoneyCalculator.metrics(
            items: try repository.wheelOfMoneyItems(),
            currentMonth: targetMonth.month
        ).remainingAverage

        XCTAssertEqual(savingsDebit.type, .fixedDebit)
        XCTAssertEqual(savingsDebit.amount, expectedAmount)
        XCTAssertNil(savingsDebit.dueDay)
        XCTAssertFalse(savingsDebit.isPaid)
        XCTAssertFalse(savingsDebit.copiesToNextMonthAutomatically)
    }

    func testPopulatingMonthCopiesAutoCopiedPreviousMonthItems() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        let sourceMonth = state.selectedMonth
        let targetMonth = nextMonth(after: sourceMonth)
        let accountID = try XCTUnwrap(try repository.accounts().first).id
        try repository.createPlannedItem(
            PlannedItem(
                accountID: accountID,
                monthKey: sourceMonth,
                type: .fixedDebit,
                label: "Rent",
                amount: 1200,
                dueDay: 1,
                isPaid: false,
                copiesToNextMonthAutomatically: true
            )
        )

        state.selectedMonth = targetMonth
        try state.refresh()
        state.populateSelectedMonthFromPrevious()

        let copiedItem = try XCTUnwrap(
            try repository.plannedItems(for: targetMonth).first(where: { $0.label == "Rent" })
        )

        XCTAssertEqual(copiedItem.source, .copiedFromPreviousMonth)
        XCTAssertEqual(copiedItem.amount, 1200)
        XCTAssertEqual(copiedItem.dueDay, 1)
        XCTAssertFalse(copiedItem.isPaid)
    }

    func testPopulatingMonthDoesNotCreateWheelOfMoneySavingsDebitWhenDisabled() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        let targetMonth = nextMonth(after: state.selectedMonth)
        let accountID = try XCTUnwrap(try repository.accounts().first).id
        try repository.createPlannedItem(
            PlannedItem(
                accountID: accountID,
                monthKey: state.selectedMonth,
                type: .fixedDebit,
                label: "Rent",
                amount: 1200,
                dueDay: 1,
                isPaid: false
            )
        )
        state.selectedMonth = targetMonth
        try state.refresh()

        state.populateSelectedMonthFromPrevious()

        XCTAssertFalse(
            try repository.plannedItems(for: targetMonth).contains(where: { $0.label == "WoM savings" })
        )
    }

    func testPopulatingMonthCreatesWheelOfMoneySavingsDebitEvenWhenPreviousMonthIsEmpty() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        try repository.createWheelOfMoneyItem(
            WheelOfMoneyItem(
                budgetID: UUID(),
                title: "Car insurance",
                amount: 900,
                month: WheelOfMoneyMonth.march.rawValue,
                isPaid: false
            )
        )
        state.autoGenerateWoMSavingsEveryMonth = true
        let targetMonth = nextMonth(after: state.selectedMonth)
        state.selectedMonth = targetMonth
        try state.refresh()

        state.populateSelectedMonthFromPrevious()

        XCTAssertTrue(
            try repository.plannedItems(for: targetMonth).contains(where: { $0.label == "WoM savings" })
        )
    }

    func testExistingWheelOfMoneySavingsDebitIsNotDuplicated() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        try repository.createWheelOfMoneyItem(
            WheelOfMoneyItem(
                budgetID: UUID(),
                title: "Car insurance",
                amount: 900,
                month: WheelOfMoneyMonth.march.rawValue,
                isPaid: false
            )
        )
        let targetMonth = nextMonth(after: state.selectedMonth)
        let accountID = try XCTUnwrap(try repository.accounts().first).id
        try repository.createPlannedItem(
            PlannedItem(
                accountID: accountID,
                monthKey: state.selectedMonth,
                type: .fixedDebit,
                label: "Rent",
                amount: 1200,
                dueDay: 1,
                isPaid: false
            )
        )
        try repository.createPlannedItem(
            PlannedItem(
                accountID: accountID,
                monthKey: targetMonth,
                type: .fixedDebit,
                label: "WoM savings",
                amount: 123,
                dueDay: nil,
                isPaid: false,
                copiesToNextMonthAutomatically: false
            )
        )
        state.autoGenerateWoMSavingsEveryMonth = true
        state.selectedMonth = targetMonth
        try state.refresh()

        state.populateSelectedMonthFromPrevious()

        let matchingDebits = try repository.plannedItems(for: targetMonth)
            .filter { $0.label == "WoM savings" }

        XCTAssertEqual(matchingDebits.count, 1)
        XCTAssertEqual(matchingDebits.first?.amount, 123)
    }

    func testCreatingWheelOfMoneyEntryUpdatesAnnualTotal() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        let originalTotal = state.wheelOfMoneyMetrics.annualTotal

        _ = state.createWheelOfMoneyEntry(
            title: "Boiler service",
            amount: 600,
            month: WheelOfMoneyMonth.october.rawValue
        )

        XCTAssertEqual(state.wheelOfMoneyMetrics.annualTotal, originalTotal + 600)
    }

    func testWheelOfMoneyRowContentShowsOnlyTrimmedNotes() {
        let item = WheelOfMoneyItem(
            budgetID: UUID(),
            title: "Christmas",
            amount: 1000,
            month: WheelOfMoneyMonth.december.rawValue,
            notes: "  Presents  "
        )
        let emptyNotes = WheelOfMoneyItem(
            budgetID: UUID(),
            title: "Car insurance",
            amount: 900,
            month: WheelOfMoneyMonth.march.rawValue,
            notes: "   "
        )

        XCTAssertEqual(WheelOfMoneyRowContent.notesLine(for: item), "Presents")
        XCTAssertNil(WheelOfMoneyRowContent.notesLine(for: emptyNotes))
    }

    func testCurrentMonthBalancePersistsAcrossAppStateRecreation() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        state.primaryBankBalance = 1234

        let reloaded = AppState(repository: repository)
        try reloaded.refresh()

        XCTAssertEqual(reloaded.primaryBankBalance, 1234)
        XCTAssertFalse((try repository.activeBudget()?.monthBalancesPayload).map(\.isEmpty) ?? true)
    }

    func testDailySeparateAccountBalancePersistsAcrossAppStateRecreation() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        state.usesSeparateAccountForDailyBudget = true
        state.dailyBudgetSeparateAccountBalance = 888

        let reloaded = AppState(repository: repository)

        XCTAssertEqual(reloaded.dailyBudgetSeparateAccountBalance, 888)
    }

    func testDailyCurrentBalanceUsesMonthProjectionWhenSeparateAccountDisabled() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()

        XCTAssertFalse(state.usesSeparateAccountForDailyBudget)
        XCTAssertEqual(state.dailyBudgetCurrentBalance, state.projectedBalanceFromCurrentBalance)
    }

    func testDailyCurrentBalanceUsesSeparateAccountBalanceWhenEnabled() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        state.usesSeparateAccountForDailyBudget = true
        state.dailyBudgetSeparateAccountBalance = 777

        XCTAssertEqual(state.dailyBudgetCurrentBalance, 777)
    }

    func testDailyBudgetCycleWrapsAcrossMonthBoundary() {
        let calendar = Self.utcCalendar
        let metrics = DailyBudgetCycleCalculator.metrics(
            today: Self.date(year: 2026, month: 4, day: 2),
            paydayDay: 1,
            budget: 3000,
            currentBalance: 2900,
            calendar: calendar
        )

        XCTAssertEqual(
            calendar.startOfDay(for: metrics.previousPayday),
            calendar.startOfDay(for: Self.date(year: 2026, month: 4, day: 1))
        )
        XCTAssertEqual(
            calendar.startOfDay(for: metrics.nextPayday),
            calendar.startOfDay(for: Self.date(year: 2026, month: 5, day: 1))
        )
        XCTAssertEqual(metrics.cycleDays, 30)
        XCTAssertEqual(metrics.elapsedDaysInCycle, 1)
        XCTAssertEqual(metrics.remainingDaysToPayday, 29)
    }

    func testDailyBudgetCycleCalculatesChipValues() {
        let metrics = DailyBudgetCycleCalculator.metrics(
            today: Self.date(year: 2026, month: 3, day: 12),
            paydayDay: 1,
            budget: 3100,
            currentBalance: 2500,
            calendar: Self.utcCalendar
        )

        XCTAssertEqual(metrics.dailyBudget, 100)
        XCTAssertEqual(metrics.expectedBalanceToday, 2000)
        XCTAssertEqual(metrics.aheadBehind, 500)
        XCTAssertEqual(metrics.currentDailyBudget, 125)
    }

    func testDailyChipToneResolverUsesWhiteBudgetCardsAndComparisonColours() {
        let metrics = DailyBudgetCycleMetrics(
            previousPayday: Self.date(year: 2026, month: 3, day: 1),
            nextPayday: Self.date(year: 2026, month: 4, day: 1),
            cycleDays: 31,
            elapsedDaysInCycle: 11,
            remainingDaysToPayday: 20,
            dailyBudget: 100,
            expectedBalanceToday: 2000,
            aheadBehind: -50,
            currentDailyBudget: 120
        )

        XCTAssertEqual(DailyChipToneResolver.tone(for: .budget, metrics: metrics, currentBalance: 500), .plain)
        XCTAssertEqual(DailyChipToneResolver.tone(for: .dailyBudget, metrics: metrics, currentBalance: 500), .plain)
        XCTAssertEqual(DailyChipToneResolver.tone(for: .aheadBehind, metrics: metrics, currentBalance: 500), .negative)
        XCTAssertEqual(DailyChipToneResolver.tone(for: .currentDailyBudget, metrics: metrics, currentBalance: 500), .positive)
    }

    func testDailyPresentationHelpersExposeUpdatedTitlesAndPaydayLabel() {
        XCTAssertEqual(
            DailyPresentationContent.balanceTitle(usesSeparateAccount: true),
            "Current balance"
        )
        XCTAssertEqual(
            DailyPresentationContent.balanceTitle(usesSeparateAccount: false),
            "Predicted remaining funds"
        )
        XCTAssertEqual(
            DailyPresentationContent.budgetTitle,
            "Starting budget"
        )
        XCTAssertEqual(
            DailyPresentationContent.daysUntilPaydayTitle(paydayDay: 17),
            "Days until payday (17th)"
        )
    }

    func testEditableMoneyChipLayoutShowsDismissButtonOnlyWhileFocused() {
        XCTAssertEqual(
            EditableMoneyChipLayout.editing,
            EditableMoneyChipLayout(isEditing: true)
        )
        XCTAssertEqual(
            EditableMoneyChipLayout.resting,
            EditableMoneyChipLayout(isEditing: false)
        )
        XCTAssertTrue(EditableMoneyChipLayout.editing.showsDismissButton)
        XCTAssertFalse(EditableMoneyChipLayout.resting.showsDismissButton)
        XCTAssertEqual(EditableMoneyChipLayout.editing.trailingAccessoryWidth, 34)
        XCTAssertEqual(EditableMoneyChipLayout.resting.trailingAccessoryWidth, 0)
    }

    func testEditableMoneyChipLayoutShowsPersistentEditBadge() {
        XCTAssertTrue(EditableMoneyChipLayout.editing.showsEditBadge)
        XCTAssertTrue(EditableMoneyChipLayout.resting.showsEditBadge)
    }

    func testChipPaletteUsesBlackTextAndGreyPlainChipsInDarkMode() {
        let palette = ChipPalette.forColorScheme(.dark)

        XCTAssertEqual(palette.titleColor, Color.black.opacity(0.65))
        XCTAssertEqual(palette.valueColor, .black)
        XCTAssertEqual(palette.plainTop, Color(red: 0.86, green: 0.86, blue: 0.86))
        XCTAssertEqual(palette.plainBottom, Color(red: 0.80, green: 0.80, blue: 0.80))
        XCTAssertEqual(palette.negativeTop, Color(red: 0.98, green: 0.90, blue: 0.90))
        XCTAssertEqual(palette.negativeBottom, Color(red: 0.94, green: 0.78, blue: 0.78))
    }

    func testChipPaletteKeepsWhitePlainChipsInLightMode() {
        let palette = ChipPalette.forColorScheme(.light)

        XCTAssertEqual(palette.titleColor, .secondary)
        XCTAssertEqual(palette.valueColor, .primary)
        XCTAssertEqual(palette.plainTop, .white)
        XCTAssertEqual(palette.plainBottom, Color(red: 0.96, green: 0.96, blue: 0.96))
        XCTAssertEqual(palette.negativeTop, Color(red: 0.98, green: 0.86, blue: 0.86))
        XCTAssertEqual(palette.negativeBottom, Color(red: 0.93, green: 0.70, blue: 0.70))
    }

    func testMonthEditableCardRulesOnlyAllowCurrentMonthBalanceEditing() {
        XCTAssertTrue(
            MonthEditableCardRules.allowsCurrentBalanceEditing(
                isSelectedMonthInPast: false,
                isSelectedMonthInFuture: false
            )
        )
        XCTAssertFalse(
            MonthEditableCardRules.allowsCurrentBalanceEditing(
                isSelectedMonthInPast: true,
                isSelectedMonthInFuture: false
            )
        )
        XCTAssertFalse(
            MonthEditableCardRules.allowsCurrentBalanceEditing(
                isSelectedMonthInPast: false,
                isSelectedMonthInFuture: true
            )
        )
    }

    func testMonthChipFocusIDChangesPerMonth() {
        let january = YearMonth(year: 2026, month: 1)
        let february = YearMonth(year: 2026, month: 2)

        XCTAssertEqual(
            MonthChipFocusID.currentBalance(for: january),
            "month-current-balance-2026-01"
        )
        XCTAssertNotEqual(
            MonthChipFocusID.currentBalance(for: january),
            MonthChipFocusID.currentBalance(for: february)
        )
    }

    func testPendingMonthFilterIncludesUnpaidCreditsAndOutgoings() {
        let month = YearMonth(year: 2026, month: 3)
        let accountID = UUID()
        let items = [
            PlannedItem(accountID: accountID, monthKey: month, type: .credit, label: "Salary", amount: 1000, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "Rent", amount: 700, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .transfer, label: "Living", amount: 200, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "Placeholder", amount: 0, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .credit, label: "Paid bonus", amount: 50, isPaid: true),
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "Paid bill", amount: 20, isPaid: true)
        ]

        XCTAssertEqual(
            MonthItemFilterRules.filteredItems(items, for: .pending).map(\.label).sorted(),
            ["Living", "Rent", "Salary"]
        )
    }

    func testPendingMonthFilterExcludesZeroValueItems() {
        let month = YearMonth(year: 2026, month: 3)
        let accountID = UUID()
        let items = [
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "Zero debit", amount: 0, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .credit, label: "Zero credit", amount: 0, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .transfer, label: "Living", amount: 200, isPaid: false)
        ]

        XCTAssertEqual(
            MonthItemFilterRules.filteredItems(items, for: .pending).map(\.label),
            ["Living"]
        )
    }

    func testMonthItemSortOrdersDueDaysFromPayday() {
        let month = YearMonth(year: 2026, month: 3)
        let accountID = UUID()
        let items = [
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "Before payday", amount: 10, dueDay: 24),
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "Payday", amount: 10, dueDay: 25),
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "Month end", amount: 10, dueDay: 31),
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "After wrap", amount: 10, dueDay: 1)
        ]

        XCTAssertEqual(
            MonthItemSortRules.sortedItems(items, paydayDay: 25).map(\.label),
            ["Payday", "Month end", "After wrap", "Before payday"]
        )
    }

    func testDefaultPersistencePlanUsesCloudBackedPrivateStoreAndSharedStore() {
        let plan = MonthlyMoneyPersistencePlan.defaultPlan()

        XCTAssertEqual(plan.privateStore.syncMode, .cloudPrivate)
        XCTAssertEqual(plan.sharedStore.syncMode, .cloudShared)
    }

    func testDefaultPersistencePlanUsesCoreDataPrivateAndSharedStores() {
        let plan = MonthlyMoneyPersistencePlan.defaultPlan()

        XCTAssertEqual(plan.privateStore.backend, .coreData)
        XCTAssertEqual(plan.sharedStore.backend, .coreData)
        XCTAssertEqual(plan.sharedStore.syncMode, .cloudShared)
    }

    func testCoreDataCloudKitProbeBuildsPrivateStoreDescription() {
        let description = CoreDataCloudKitProbe.makeStoreDescription(
            url: URL(fileURLWithPath: "/tmp/private.sqlite"),
            scope: .privateDatabase,
            containerIdentifier: "iCloud.com.hatbat.monthlymoney"
        )

        XCTAssertEqual(description.url?.path, "/tmp/private.sqlite")
        XCTAssertEqual(description.cloudKitContainerOptions?.containerIdentifier, "iCloud.com.hatbat.monthlymoney")
        XCTAssertEqual(description.cloudKitContainerOptions?.databaseScope, .private)
        let options = description.value(forKey: "options") as? [String: Any]
        XCTAssertEqual(options?[NSPersistentHistoryTrackingKey] as? Bool, true)
        XCTAssertEqual(options?[NSPersistentStoreRemoteChangeNotificationPostOptionKey] as? Bool, true)
        XCTAssertTrue(description.shouldMigrateStoreAutomatically)
        XCTAssertTrue(description.shouldInferMappingModelAutomatically)
    }

    func testCoreDataCloudKitProbeBuildsSharedStoreDescription() {
        let description = CoreDataCloudKitProbe.makeStoreDescription(
            url: URL(fileURLWithPath: "/tmp/shared.sqlite"),
            scope: .sharedDatabase,
            containerIdentifier: "iCloud.com.hatbat.monthlymoney"
        )

        XCTAssertEqual(description.url?.path, "/tmp/shared.sqlite")
        XCTAssertEqual(description.cloudKitContainerOptions?.containerIdentifier, "iCloud.com.hatbat.monthlymoney")
        XCTAssertEqual(description.cloudKitContainerOptions?.databaseScope, .shared)
        let options = description.value(forKey: "options") as? [String: Any]
        XCTAssertEqual(options?[NSPersistentHistoryTrackingKey] as? Bool, true)
        XCTAssertEqual(options?[NSPersistentStoreRemoteChangeNotificationPostOptionKey] as? Bool, true)
        XCTAssertTrue(description.shouldMigrateStoreAutomatically)
        XCTAssertTrue(description.shouldInferMappingModelAutomatically)
    }

    func testCoreDataAccountDataStoreRoundTripsBudgetAccountsItemsAndTransactions() throws {
        let store = try CoreDataAccountDataStore.makeInMemory()
        Self.retainHostedTestObject(store)

        let budget = Budget(
            id: UUID(),
            name: "Household",
            ownerParticipantID: "owner",
            sharingState: .local,
            usesSeparateAccountForDailyBudget: true,
            dailyBudgetAmount: 1500,
            dailyBudgetPaydayDay: 25
        )
        try store.upsertBudget(budget)

        let account = Account(
            id: UUID(),
            budgetID: budget.id,
            name: "Joint",
            role: .regular,
            type: .current,
            ownerParticipantID: "owner"
        )
        try store.upsertAccount(account)

        let item = PlannedItem(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            monthKey: YearMonth(year: 2026, month: 3),
            type: .fixedDebit,
            label: "Rent",
            amount: 1200,
            matchingString: "Council tax",
            dueDay: 1,
            isPaid: false,
            copiesToNextMonthAutomatically: true,
            notes: "Landlord"
        )
        try store.upsertPlannedItems([item])

        let transaction = Transaction(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            monthKey: YearMonth(year: 2026, month: 3),
            amount: 1200,
            note: "Rent payment",
            sourceKind: "nationwide_ofx",
            sourceExternalTransactionID: "FITID-TRANSACTION-1",
            sourcePostedAt: Date(timeIntervalSince1970: 1_234.5)
        )
        try store.upsertTransactions([transaction])

        let budgets = try store.fetchBudgets()
        XCTAssertEqual(budgets.map(\.id), [budget.id])
        XCTAssertEqual(budgets.first?.usesSeparateAccountForDailyBudget, true)
        XCTAssertEqual(budgets.first?.dailyBudgetAmount, 1500)
        XCTAssertEqual(budgets.first?.dailyBudgetPaydayDay, 25)
        let accounts = try store.fetchAccounts()
        XCTAssertEqual(accounts.map(\.id), [account.id])
        let plannedItems = try store.fetchPlannedItems(accountIDs: [account.id], monthKey: YearMonth(year: 2026, month: 3))
        XCTAssertEqual(
            plannedItems.map(\.id),
            [item.id]
        )
        XCTAssertEqual(plannedItems.first?.matchingString, "Council tax")
        let transactions = try store.fetchTransactions(accountIDs: [account.id])
        XCTAssertEqual(
            transactions.map(\.id),
            [transaction.id]
        )
        XCTAssertEqual(transactions.first?.sourceKind, "nationwide_ofx")
        XCTAssertEqual(transactions.first?.sourceExternalTransactionID, "FITID-TRANSACTION-1")
        XCTAssertEqual(transactions.first?.sourcePostedAt, Date(timeIntervalSince1970: 1_234.5))
        XCTAssertEqual(plannedItems.first?.source, .manual)

        let container = NSPersistentContainer(
            name: "MonthlyMoneyCoreData",
            managedObjectModel: CoreDataModelBuilder.sharedModel
        )
        let description = NSPersistentStoreDescription()
        description.type = NSInMemoryStoreType
        description.shouldAddStoreAsynchronously = false
        container.persistentStoreDescriptions = [description]

        var loadError: Error?
        container.loadPersistentStores { _, error in
            loadError = error
        }
        if let loadError {
            throw loadError
        }

        let context = container.viewContext
        let copiedItem = PlannedItem(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            monthKey: YearMonth(year: 2026, month: 3),
            type: .fixedDebit,
            source: .copiedFromPreviousMonth,
            label: "Utilities",
            amount: 75,
            dueDay: 2,
            isPaid: false,
            copiesToNextMonthAutomatically: true,
            notes: "Copied source check"
        )
        let copiedItemObject = NSEntityDescription.insertNewObject(
            forEntityName: CoreDataEntityName.plannedItem,
            into: context
        )
        CoreDataMapping.apply(copiedItem, to: copiedItemObject)
        try context.save()

        let roundTripStore = CoreDataAccountDataStore(persistentContainer: container)
        let copiedPlannedItems = try roundTripStore.fetchPlannedItems(
            accountIDs: [account.id],
            monthKey: YearMonth(year: 2026, month: 3)
        )
        let persistedCopiedItem = try XCTUnwrap(copiedPlannedItems.first { $0.id == copiedItem.id })
        XCTAssertEqual(persistedCopiedItem.source, .copiedFromPreviousMonth)
    }

    func testCoreDataAccountDataStoreMergesRemoteChangesIntoViewContext() throws {
        let store = try CoreDataAccountDataStore.makeInMemory()
        Self.retainHostedTestObject(store)

        XCTAssertTrue(store.mergesRemoteChangesAutomatically)
    }

    func testCoreDataAccountDataStoreResolvesManagedBudgetObjectID() throws {
        let store = try CoreDataAccountDataStore.makeInMemory()
        Self.retainHostedTestObject(store)

        let budget = Budget(
            id: UUID(),
            name: "Shared Household",
            ownerParticipantID: "owner",
            sharingState: .shared
        )
        try store.upsertBudget(budget)

        XCTAssertNotNil(try store.managedBudgetObjectID(for: budget.id))
    }

    func testCoreDataModelBuilderDefinesBudgetDependentRelationships() {
        let model = CoreDataModelBuilder.sharedModel
        let budgetEntity = try? XCTUnwrap(model.entitiesByName[CoreDataEntityName.budget])
        let accountEntity = try? XCTUnwrap(model.entitiesByName[CoreDataEntityName.account])
        let plannedItemEntity = try? XCTUnwrap(model.entitiesByName[CoreDataEntityName.plannedItem])
        let transactionEntity = try? XCTUnwrap(model.entitiesByName[CoreDataEntityName.transaction])
        let importedTransactionRecordEntity = try? XCTUnwrap(model.entitiesByName[CoreDataEntityName.importedTransactionRecord])
        let wheelOfMoneyItemEntity = try? XCTUnwrap(model.entitiesByName[CoreDataEntityName.wheelOfMoneyItem])

        let budgetRelationshipNames = Set(budgetEntity?.relationshipsByName.keys ?? Dictionary<String, NSRelationshipDescription>().keys)
        XCTAssertEqual(
            budgetRelationshipNames,
            ["accounts", "plannedItems", "transactions", "importedTransactionRecords", "wheelOfMoneyItems"]
        )

        XCTAssertEqual(accountEntity?.relationshipsByName["budget"]?.destinationEntity?.name, CoreDataEntityName.budget)
        XCTAssertEqual(plannedItemEntity?.relationshipsByName["budget"]?.destinationEntity?.name, CoreDataEntityName.budget)
        XCTAssertEqual(transactionEntity?.relationshipsByName["budget"]?.destinationEntity?.name, CoreDataEntityName.budget)
        XCTAssertEqual(importedTransactionRecordEntity?.relationshipsByName["budget"]?.destinationEntity?.name, CoreDataEntityName.budget)
        XCTAssertEqual(wheelOfMoneyItemEntity?.relationshipsByName["budget"]?.destinationEntity?.name, CoreDataEntityName.budget)
    }

    func testCoreDataAccountDataStoreAttachesDependentsToBudgetRelationships() throws {
        let store = try CoreDataAccountDataStore.makeInMemory()
        Self.retainHostedTestObject(store)

        let budget = Budget(
            id: UUID(),
            name: "Household",
            ownerParticipantID: "owner",
            sharingState: .local
        )
        try store.upsertBudget(budget)

        let account = Account(
            id: UUID(),
            budgetID: budget.id,
            name: "Joint",
            role: .regular,
            type: .current,
            ownerParticipantID: "owner"
        )
        try store.upsertAccount(account)

        let item = PlannedItem(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            monthKey: YearMonth(year: 2026, month: 3),
            type: .fixedDebit,
            label: "Rent",
            amount: 1200,
            dueDay: 1
        )
        try store.upsertPlannedItems([item])

        let transaction = Transaction(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            monthKey: YearMonth(year: 2026, month: 3),
            amount: 1200,
            note: "Rent"
        )
        try store.upsertTransactions([transaction])

        let importedRecord = ImportedTransactionRecord(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            sourceKind: "nationwide_ofx",
            sourceAccountIdentifier: "****81197",
            externalTransactionID: "FITID-1",
            postedAt: Date(timeIntervalSince1970: 1_000),
            amount: -12.34,
            payee: "Test Payee",
            transactionType: "POS",
            rawSourcePayload: "{\"fitid\":\"FITID-1\"}",
            importedAt: Date(timeIntervalSince1970: 1_100),
            appliedPlannedItemID: UUID(),
            createdTransactionID: UUID()
        )
        try store.upsertImportedTransactionRecords([importedRecord])

        let counts = try store.budgetRelationshipCounts(for: budget.id)
        XCTAssertEqual(counts.accounts, 1)
        XCTAssertEqual(counts.plannedItems, 1)
        XCTAssertEqual(counts.transactions, 1)
        XCTAssertEqual(counts.importedTransactionRecords, 1)
    }

    func testCoreDataAccountDataStoreRoundTripsImportedTransactionRecords() throws {
        let store = try CoreDataAccountDataStore.makeInMemory()
        Self.retainHostedTestObject(store)

        let budget = Budget(
            id: UUID(),
            name: "Household",
            ownerParticipantID: "owner",
            sharingState: .local
        )
        try store.upsertBudget(budget)

        let account = Account(
            id: UUID(),
            budgetID: budget.id,
            name: "Joint",
            role: .regular,
            type: .current,
            ownerParticipantID: "owner"
        )
        try store.upsertAccount(account)

        let record = ImportedTransactionRecord(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            sourceKind: "nationwide_ofx",
            sourceAccountIdentifier: "****81197",
            externalTransactionID: "FITID-ROUNDTRIP",
            postedAt: Date(timeIntervalSince1970: 1_000),
            amount: -42.50,
            payee: "Roundtrip Payee",
            transactionType: "DIRECTDEBIT",
            rawSourcePayload: "{\"fitid\":\"FITID-ROUNDTRIP\"}",
            importedAt: Date(timeIntervalSince1970: 1_100),
            appliedPlannedItemID: UUID(),
            createdTransactionID: UUID()
        )

        try store.upsertImportedTransactionRecords([record])

        let fetched = try store.fetchImportedTransactionRecords(accountIDs: [account.id])
        XCTAssertEqual(fetched.map(\.externalTransactionID), ["FITID-ROUNDTRIP"])
        XCTAssertEqual(fetched.first?.rawSourcePayload, "{\"fitid\":\"FITID-ROUNDTRIP\"}")
        XCTAssertNotNil(fetched.first?.appliedPlannedItemID)
        XCTAssertNotNil(fetched.first?.createdTransactionID)
    }

    func testCoreDataAccountDataStoreBackfillsBudgetRelationshipsForExistingDependents() throws {
        let container = NSPersistentContainer(
            name: "MonthlyMoneyCoreData",
            managedObjectModel: CoreDataModelBuilder.sharedModel
        )
        let description = NSPersistentStoreDescription()
        description.type = NSInMemoryStoreType
        description.shouldAddStoreAsynchronously = false
        container.persistentStoreDescriptions = [description]

        var loadError: Error?
        container.loadPersistentStores { _, error in
            loadError = error
        }
        if let loadError {
            throw loadError
        }

        let context = container.viewContext
        let budget = Budget(
            id: UUID(),
            name: "Household",
            ownerParticipantID: "owner",
            sharingState: .local
        )

        let budgetObject = NSEntityDescription.insertNewObject(
            forEntityName: CoreDataEntityName.budget,
            into: context
        )
        CoreDataMapping.apply(budget, to: budgetObject)

        let account = Account(
            id: UUID(),
            budgetID: budget.id,
            name: "Joint",
            role: .regular,
            type: .current,
            ownerParticipantID: "owner"
        )
        let accountObject = NSEntityDescription.insertNewObject(
            forEntityName: CoreDataEntityName.account,
            into: context
        )
        CoreDataMapping.apply(account, to: accountObject)

        let item = PlannedItem(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            monthKey: YearMonth(year: 2026, month: 3),
            type: .fixedDebit,
            label: "Rent",
            amount: 1200,
            dueDay: 1
        )
        item.source = .copiedFromPreviousMonth
        let itemObject = NSEntityDescription.insertNewObject(
            forEntityName: CoreDataEntityName.plannedItem,
            into: context
        )
        CoreDataMapping.apply(item, to: itemObject)

        let transaction = Transaction(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            monthKey: YearMonth(year: 2026, month: 3),
            amount: 1200,
            note: "Rent"
        )
        let transactionObject = NSEntityDescription.insertNewObject(
            forEntityName: CoreDataEntityName.transaction,
            into: context
        )
        CoreDataMapping.apply(transaction, to: transactionObject)

        try context.save()

        let store = CoreDataAccountDataStore(persistentContainer: container)
        Self.retainHostedTestObject(store)
        let beforeCounts = try store.budgetRelationshipCounts(for: budget.id)
        XCTAssertEqual(beforeCounts.accounts, 0)
        XCTAssertEqual(beforeCounts.plannedItems, 0)
        XCTAssertEqual(beforeCounts.transactions, 0)
        XCTAssertEqual(beforeCounts.importedTransactionRecords, 0)

        try store.repairBudgetRelationships(for: budget.id)

        let afterCounts = try store.budgetRelationshipCounts(for: budget.id)
        XCTAssertEqual(afterCounts.accounts, 1)
        XCTAssertEqual(afterCounts.plannedItems, 1)
        XCTAssertEqual(afterCounts.transactions, 1)
        XCTAssertEqual(afterCounts.importedTransactionRecords, 0)
    }

    func testBootstrapRulesWaitForCloudImportOnlyForEmptyCloudBackedPrivateStore() {
        XCTAssertTrue(
            AppBootstrapRules.shouldWaitForInitialCloudImport(
                privateStoreSyncMode: .cloudPrivate,
                accountCount: 0
            )
        )
        XCTAssertFalse(
            AppBootstrapRules.shouldWaitForInitialCloudImport(
                privateStoreSyncMode: .cloudPrivate,
                accountCount: 1
            )
        )
        XCTAssertFalse(
            AppBootstrapRules.shouldWaitForInitialCloudImport(
                privateStoreSyncMode: .localOnly,
                accountCount: 0
            )
        )
    }

    func testRepositoryDelegatesInitialPrivateCloudImportWaitToPrivateStore() async throws {
        let privateStore = AwaitingAccountDataStoreSpy()
        let repository = AccountRepository(
            privateStore: privateStore,
            sharedStore: InMemoryAccountDataStore(),
            privateStoreSyncMode: .cloudPrivate
        )

        try await repository.awaitInitialPrivateCloudImport(timeout: .seconds(3))

        XCTAssertTrue(privateStore.didAwaitInitialCloudImport)
    }

    func testPersistenceFactoryBuildsCoreDataPrivateAndSharedStores() throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let repository = try MonthlyMoneyPersistenceFactory.makeRepository(
            plan: .defaultPlan(baseDirectory: directory),
            schema: Self.makeSchema()
        )
        Self.retainHostedTestObject(repository)

        XCTAssertEqual(repository.privateStoreImplementationKind, .coreData)
        XCTAssertEqual(repository.sharedStoreImplementationKind, .coreData)
        XCTAssertEqual(repository.sharedStoreSyncMode, .cloudShared)
    }

    func testCloudKitShareSceneConfigurationUsesShareSceneDelegate() {
        let configuration = CloudKitShareSceneConfiguration.make(for: .windowApplication)

        XCTAssertTrue(configuration.delegateClass == MonthlyMoneyCloudKitShareSceneDelegate.self)
    }

    func testWheelOfMoneySavingsSettingPersistsInProductionRepository() async throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let repository = try MonthlyMoneyPersistenceFactory.makeRepository(
            plan: .defaultPlan(baseDirectory: directory),
            schema: Self.makeSchema()
        )
        Self.retainHostedTestObject(repository)

        let state = AppState(repository: repository)
        await state.bootstrapIfNeeded()
        XCTAssertFalse(state.autoGenerateWoMSavingsEveryMonth)

        state.autoGenerateWoMSavingsEveryMonth = true

        let reloaded = AppState(repository: repository)
        try reloaded.refresh()

        XCTAssertTrue(reloaded.autoGenerateWoMSavingsEveryMonth)
        XCTAssertEqual(try repository.activeBudget()?.autoGenerateWoMSavingsEveryMonth, true)
    }

    func testCloudKitShareAcceptancePolicyOnlyProcessesWhenMetadataExists() {
        XCTAssertFalse(CloudKitShareAcceptancePolicy.shouldProcess(pendingMetadataCount: 0))
        XCTAssertTrue(CloudKitShareAcceptancePolicy.shouldProcess(pendingMetadataCount: 1))
    }

    func testCloudKitShareAcceptanceDispatcherStartsAcceptanceForPendingMetadata() {
        var drained = false
        var accepted: [Int] = []

        CloudKitShareAcceptanceDispatcher.dispatchIfNeeded(
            pendingMetadataCount: 1,
            drain: {
                drained = true
                return [1, 2]
            },
            start: { accepted = $0 }
        )

        XCTAssertTrue(drained)
        XCTAssertEqual(accepted, [1, 2])
    }

    func testCloudKitShareAcceptanceDispatcherDoesNothingWhenNoMetadataIsPending() {
        var drained = false
        var didStart = false

        CloudKitShareAcceptanceDispatcher.dispatchIfNeeded(
            pendingMetadataCount: 0,
            drain: {
                drained = true
                return [1]
            },
            start: { _ in didStart = true }
        )

        XCTAssertFalse(drained)
        XCTAssertFalse(didStart)
    }

    func testSettingsSharingPresentationForLocalBudget() {
        let presentation = SettingsSharingPresentation(status: .localOnly)

        XCTAssertEqual(presentation.statusText, "Local only")
        XCTAssertTrue(presentation.isShareButtonEnabled)
        XCTAssertNil(presentation.note)
    }

    func testSettingsSharingPresentationForOwnerSharedBudget() {
        let presentation = SettingsSharingPresentation(status: .sharedByYou)

        XCTAssertEqual(presentation.statusText, "Shared by you")
        XCTAssertTrue(presentation.isShareButtonEnabled)
        XCTAssertTrue(presentation.showsUnshareButton)
        XCTAssertNil(presentation.note)
    }

    func testSettingsSharingPresentationForRecipientSharedBudget() {
        let presentation = SettingsSharingPresentation(status: .sharedWithYou)

        XCTAssertEqual(presentation.statusText, "Shared with you")
        XCTAssertFalse(presentation.isShareButtonEnabled)
        XCTAssertFalse(presentation.showsUnshareButton)
        XCTAssertNil(presentation.note)
    }

    func testSettingsSharingPresentationForSharedBudgetAvailable() {
        let presentation = SettingsSharingPresentation(status: .sharedAvailable)

        XCTAssertEqual(presentation.statusText, "Shared budget available")
        XCTAssertFalse(presentation.isShareButtonEnabled)
        XCTAssertFalse(presentation.showsUnshareButton)
        XCTAssertEqual(presentation.note, "Open the shared budget from the overwrite prompt when you're ready.")
    }

    func testShareMetadataConfiguratorSetsTitleAndType() {
        let rootRecord = CKRecord(recordType: "Budget")
        let share = CKShare(rootRecord: rootRecord)

        ShareMetadataConfigurator.apply(to: share, budgetName: "Joint Budget")

        XCTAssertEqual(share[CKShare.SystemFieldKey.title] as? String, ShareMetadataConfigurator.appDisplayName)
        XCTAssertEqual(share[CKShare.SystemFieldKey.shareType] as? String, ShareMetadataConfigurator.itemType)
    }

    func testSettingsSharingPresentationForLocalBudgetDoesNotShowUnshare() {
        let presentation = SettingsSharingPresentation(status: .localOnly)

        XCTAssertFalse(presentation.showsUnshareButton)
    }

    func testAppStateSharingStatusReflectsActiveBudget() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        XCTAssertEqual(state.sharingStatus, .localOnly)

        let budget = try XCTUnwrap(try repository.activeBudget())
        budget.sharingState = .shared
        budget.ownerParticipantID = "owner"
        try repository.saveBudget(budget)
        XCTAssertEqual(state.sharingStatus, .sharedByYou)

        budget.ownerParticipantID = "jane"
        try repository.saveBudget(budget)
        XCTAssertEqual(state.sharingStatus, .sharedWithYou)
    }

    func testAppStateSharingStatusReflectsSharedBudgetAvailableBeforeAdoption() async throws {
        let repository = try makeRepository()
        let state = AppState(
            repository: repository,
            currentParticipantIDProvider: { "rog" }
        )

        await state.bootstrapIfNeeded()
        try insertIncomingSharedBudget(into: repository, month: state.selectedMonth)

        try state.refresh()

        XCTAssertEqual(state.sharingStatus, .sharedAvailable)
    }

    func testBudgetSettingsAreEditableForLocalAndOwnerSharedBudgets() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        XCTAssertTrue(state.canEditBudgetSettings)

        state.usesSeparateAccountForDailyBudget = true
        XCTAssertTrue(state.usesSeparateAccountForDailyBudget)

        let budget = try XCTUnwrap(try repository.activeBudget())
        budget.sharingState = .shared
        budget.ownerParticipantID = "owner"
        try repository.saveBudget(budget)

        XCTAssertTrue(state.canEditBudgetSettings)

        state.usesSeparateAccountForDailyBudget = false
        XCTAssertFalse(state.usesSeparateAccountForDailyBudget)
    }

    func testWheelOfMoneySavingsSettingPersistsOnActiveBudget() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        XCTAssertFalse(state.autoGenerateWoMSavingsEveryMonth)

        state.autoGenerateWoMSavingsEveryMonth = true

        XCTAssertTrue(state.autoGenerateWoMSavingsEveryMonth)
        XCTAssertEqual(try repository.activeBudget()?.autoGenerateWoMSavingsEveryMonth, true)

        state.autoGenerateWoMSavingsEveryMonth = false

        XCTAssertFalse(state.autoGenerateWoMSavingsEveryMonth)
        XCTAssertEqual(try repository.activeBudget()?.autoGenerateWoMSavingsEveryMonth, false)
    }

    func testWheelOfMoneySavingsSettingPersistsAcrossAppStateRecreation() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        state.autoGenerateWoMSavingsEveryMonth = true

        let reloaded = AppState(repository: repository)
        try reloaded.refresh()

        XCTAssertTrue(reloaded.autoGenerateWoMSavingsEveryMonth)
        XCTAssertEqual(try repository.activeBudget()?.autoGenerateWoMSavingsEveryMonth, true)
    }

    func testBudgetSettingsAreReadOnlyForParticipantSharedBudgets() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()

        let budget = try XCTUnwrap(try repository.activeBudget())
        budget.sharingState = .shared
        budget.ownerParticipantID = "jane"
        budget.usesSeparateAccountForDailyBudget = true
        try repository.saveBudget(budget)

        XCTAssertFalse(state.canEditBudgetSettings)
        XCTAssertTrue(state.usesSeparateAccountForDailyBudget)

        state.usesSeparateAccountForDailyBudget = false

        XCTAssertTrue(state.usesSeparateAccountForDailyBudget)
        XCTAssertEqual(try repository.activeBudget()?.usesSeparateAccountForDailyBudget, true)
    }

    func testBudgetSettingsRemainEditableWhileSharedBudgetIsOnlyAvailable() async throws {
        let repository = try makeRepository()
        let state = AppState(
            repository: repository,
            currentParticipantIDProvider: { "rog" }
        )

        await state.bootstrapIfNeeded()
        try insertIncomingSharedBudget(into: repository, month: state.selectedMonth)
        try state.refresh()

        XCTAssertEqual(state.sharingStatus, .sharedAvailable)
        XCTAssertTrue(state.canEditBudgetSettings)
    }

    func testShareBudgetMarksInProgressAndEndsSharedByOwner() async throws {
        let repository = try makeRepository()
        let expectation = expectation(description: "share handler called while progress flag is set")
        var observedState: AppState?
        let state = AppState(
            repository: repository,
            shareBudgetAction: { repository in
                let service = BudgetSharingService(repository: repository) { _ in
                    XCTAssertTrue(observedState?.isSharingBudget ?? false)
                    expectation.fulfill()
                }
                let sharedBudget = try service.shareBudget(participantsSelection: [])
                return BudgetShareResult(
                    sharedBudget: sharedBudget,
                    shareSession: self.makeTestBudgetShareSession(budgetID: sharedBudget.id)
                )
            }
        )
        observedState = state

        await state.bootstrapIfNeeded()
        XCTAssertFalse(state.isSharingBudget)

        await state.shareBudget()

        await fulfillment(of: [expectation], timeout: 1)
        XCTAssertFalse(state.isSharingBudget)
        XCTAssertEqual(state.sharingStatus, .sharedByYou)
        XCTAssertNotNil(try repository.localBudget())
        XCTAssertNil(try repository.sharedBudget())
        XCTAssertEqual(try repository.localBudget()?.sharingState, .shared)
        XCTAssertEqual(state.pendingBudgetShareResult?.sharedBudget.id, try repository.activeBudget()?.id)
        XCTAssertEqual(state.pendingBudgetShareResult?.shareSession.budgetID, try repository.activeBudget()?.id)
    }

    func testShareBudgetReopensForOwnerSharedBudget() async throws {
        let repository = try makeRepository()
        let expectation = expectation(description: "share handler called for already shared owner budget")
        let state = AppState(
            repository: repository,
            shareBudgetAction: { repository in
                let sharedBudget = try BudgetSharingService(repository: repository) { _ in
                    expectation.fulfill()
                }.shareBudget(participantsSelection: [])
                return BudgetShareResult(
                    sharedBudget: sharedBudget,
                    shareSession: self.makeTestBudgetShareSession(budgetID: sharedBudget.id)
                )
            }
        )

        await state.bootstrapIfNeeded()
        let budget = try XCTUnwrap(try repository.activeBudget())
        budget.sharingState = .shared
        try repository.saveBudget(budget)

        await state.shareBudget()

        await fulfillment(of: [expectation], timeout: 1)
        XCTAssertFalse(state.isSharingBudget)
        XCTAssertNil(state.sharingErrorMessage)
        XCTAssertNotNil(state.pendingBudgetShareResult)
    }

    func testHandleStopSharingReturnsOwnerBudgetToLocalState() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        let budget = try XCTUnwrap(try repository.activeBudget())
        budget.sharingState = .shared
        budget.ownerParticipantID = "owner"
        try repository.saveBudget(budget)
        try state.refresh()

        XCTAssertEqual(state.sharingStatus, .sharedByYou)

        try await state.handleBudgetShareStopped()

        XCTAssertEqual(try repository.activeBudget()?.sharingState, .local)
        XCTAssertEqual(state.sharingStatus, .localOnly)
    }

    func testHandleStopSharingKeepsBudgetSharedWhenVerificationFails() async throws {
        let repository = try makeRepository()
        let state = AppState(
            repository: repository,
            verifyBudgetUnsharedAction: { _, _ in false }
        )

        await state.bootstrapIfNeeded()
        let budget = try XCTUnwrap(try repository.activeBudget())
        budget.sharingState = .shared
        budget.ownerParticipantID = "owner"
        try repository.saveBudget(budget)
        try state.refresh()

        await state.handleBudgetShareStoppedFromUI()

        XCTAssertEqual(try repository.activeBudget()?.sharingState, .shared)
        XCTAssertEqual(state.sharingStatus, .sharedByYou)
        XCTAssertEqual(state.sharingErrorMessage, "Could not confirm that sharing was removed.")
    }

    func testClearingBudgetSharePresentationRemovesPendingShareResult() async throws {
        let repository = try makeRepository()
        let state = AppState(
            repository: repository,
            shareBudgetAction: { repository in
                let sharedBudget = try BudgetSharingService(repository: repository).shareBudget(participantsSelection: [])
                return BudgetShareResult(
                    sharedBudget: sharedBudget,
                    shareSession: self.makeTestBudgetShareSession(budgetID: sharedBudget.id)
                )
            }
        )

        await state.bootstrapIfNeeded()
        await state.shareBudget()
        XCTAssertNotNil(state.pendingBudgetShareResult)

        state.clearPendingBudgetSharePresentation()

        XCTAssertNil(state.pendingBudgetShareResult)
    }

    func testRefreshShowsPendingSharedBudgetOverwriteForRecipient() async throws {
        let repository = try makeRepository()
        let state = AppState(
            repository: repository,
            currentParticipantIDProvider: { "rog" }
        )

        await state.bootstrapIfNeeded()
        try insertIncomingSharedBudget(into: repository, month: state.selectedMonth)

        try state.refresh()

        XCTAssertTrue(state.shouldShowSharedBudgetOverwriteAlert)
        XCTAssertEqual(state.pendingSharedBudgetAdoption?.budgetName, "Shared Household")
    }

    func testConfirmSharedBudgetOverwriteDeletesLocalBudgetAndAdoptsSharedBudget() async throws {
        let repository = try makeRepository()
        let state = AppState(
            repository: repository,
            currentParticipantIDProvider: { "rog" }
        )

        await state.bootstrapIfNeeded()
        try insertIncomingSharedBudget(into: repository, month: state.selectedMonth)
        try state.refresh()

        XCTAssertTrue(state.shouldShowSharedBudgetOverwriteAlert)

        try state.confirmSharedBudgetOverwrite()

        XCTAssertNil(try repository.localBudget())
        XCTAssertEqual(try repository.activeBudget()?.sharingState, .shared)
        XCTAssertEqual(state.primaryBankName, "Shared Monzo")
        XCTAssertFalse(state.shouldShowSharedBudgetOverwriteAlert)
        XCTAssertEqual(state.monthItems.map(\.label), ["Shared Rent"])
        XCTAssertEqual(state.wheelOfMoneyItems.map(\.title), ["Shared Christmas"])
    }

    func testCancelSharedBudgetOverwriteKeepsLocalBudgetActive() async throws {
        let repository = try makeRepository()
        let state = AppState(
            repository: repository,
            currentParticipantIDProvider: { "rog" }
        )

        await state.bootstrapIfNeeded()
        let localBudgetID = try XCTUnwrap(try repository.localBudget()?.id)
        try insertIncomingSharedBudget(into: repository, month: state.selectedMonth)
        try state.refresh()

        state.cancelSharedBudgetOverwrite()

        XCTAssertEqual(try repository.localBudget()?.id, localBudgetID)
        XCTAssertEqual(try repository.activeBudget()?.sharingState, .local)
        XCTAssertFalse(state.shouldShowSharedBudgetOverwriteAlert)

        try state.refresh()
        XCTAssertFalse(state.shouldShowSharedBudgetOverwriteAlert)
    }

    func testRefreshRecreatesLocalBudgetWhenSharedBudgetDisappearsAfterAdoption() async throws {
        let repository = try makeRepository()
        let state = AppState(
            repository: repository,
            currentParticipantIDProvider: { "rog" }
        )

        await state.bootstrapIfNeeded()
        try insertIncomingSharedBudget(into: repository, month: state.selectedMonth)
        try state.refresh()
        try state.confirmSharedBudgetOverwrite()

        let sharedBudgetID = try XCTUnwrap(try repository.sharedBudget()?.id)
        try repository.deleteBudget(id: sharedBudgetID)

        try state.refresh()

        XCTAssertEqual(try repository.activeBudget()?.sharingState, .local)
        XCTAssertNotNil(try repository.localBudget())
        XCTAssertTrue(state.monthItems.isEmpty)
        XCTAssertEqual(state.primaryBankBalance, 0)
        XCTAssertEqual(state.primaryBankName, "Nationwide")
    }

    func testSharedBudgetOwnedByResolvedParticipantIsSharedByYou() async throws {
        let repository = try makeRepository()
        let state = AppState(
            repository: repository,
            currentParticipantIDProvider: { "rog" }
        )

        await state.bootstrapIfNeeded()

        let budget = try XCTUnwrap(try repository.activeBudget())
        budget.sharingState = .shared
        budget.ownerParticipantID = "rog"
        try repository.saveBudget(budget)

        try state.refresh()

        XCTAssertEqual(state.sharingStatus, .sharedByYou)
        XCTAssertFalse(state.shouldShowSharedBudgetOverwriteAlert)
    }

    func testBootstrapMigratesLegacyLocalOwnerIdentifier() async throws {
        let repository = try makeRepository()
        let legacyBudget = Budget(
            id: UUID(),
            name: "Budget",
            ownerParticipantID: "owner",
            sharingState: .local
        )
        try repository.saveBudget(legacyBudget)

        let state = AppState(
            repository: repository,
            currentParticipantIDProvider: { "rog" }
        )

        await state.bootstrapIfNeeded()

        XCTAssertEqual(try repository.localBudget()?.ownerParticipantID, "rog")
        XCTAssertEqual(state.sharingStatus, .localOnly)
    }

    func testCloudRefreshPolicyOnlyPollsForActiveCloudBackedAppSessions() {
        XCTAssertTrue(
            CloudRefreshPolicy.shouldPoll(
                privateStoreSyncMode: .cloudPrivate,
                sharedStoreSyncMode: .localOnly,
                scenePhase: .active,
                isRunningTests: false
            )
        )
        XCTAssertTrue(
            CloudRefreshPolicy.shouldPoll(
                privateStoreSyncMode: .localOnly,
                sharedStoreSyncMode: .cloudShared,
                scenePhase: .active,
                isRunningTests: false
            )
        )
        XCTAssertFalse(
            CloudRefreshPolicy.shouldPoll(
                privateStoreSyncMode: .localOnly,
                sharedStoreSyncMode: .localOnly,
                scenePhase: .active,
                isRunningTests: false
            )
        )
        XCTAssertFalse(
            CloudRefreshPolicy.shouldPoll(
                privateStoreSyncMode: .cloudPrivate,
                sharedStoreSyncMode: .cloudShared,
                scenePhase: .background,
                isRunningTests: false
            )
        )
        XCTAssertFalse(
            CloudRefreshPolicy.shouldPoll(
                privateStoreSyncMode: .cloudPrivate,
                sharedStoreSyncMode: .cloudShared,
                scenePhase: .active,
                isRunningTests: true
            )
        )
    }

    func testAcceptSharedBudgetErrorMessageIncludesUnderlyingErrorContext() throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)
        let underlying = NSError(
            domain: "CKErrorDomain",
            code: 42,
            userInfo: [NSLocalizedDescriptionKey: "Invitation is not valid."]
        )

        XCTAssertEqual(
            state.debugAcceptSharedBudgetErrorMessage(for: underlying),
            "Failed to accept shared budget: Invitation is not valid. (CKErrorDomain 42)"
        )
    }

    func testAcceptSharedBudgetErrorMessageIncludesPartialFailureDetails() throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)
        let itemError = NSError(
            domain: CKError.errorDomain,
            code: CKError.zoneNotFound.rawValue,
            userInfo: [NSLocalizedDescriptionKey: "Zone not found."]
        )
        let partialFailure = NSError(
            domain: CKError.errorDomain,
            code: CKError.partialFailure.rawValue,
            userInfo: [CKPartialErrorsByItemIDKey: ["share-1": itemError]]
        )

        XCTAssertEqual(
            state.debugAcceptSharedBudgetErrorMessage(for: partialFailure),
            "Failed to accept shared budget: Zone not found. (CKErrorDomain 26)"
        )
    }

    func testPastMonthMutationsAreIgnored() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()

        let currentMonth = state.selectedMonth
        let pastMonth = YearMonth(year: currentMonth.month == 1 ? currentMonth.year - 1 : currentMonth.year,
                                  month: currentMonth.month == 1 ? 12 : currentMonth.month - 1)
        let account = try XCTUnwrap(try repository.accounts().first)
        let item = PlannedItem(
            accountID: account.id,
            monthKey: pastMonth,
            type: .fixedDebit,
            label: "Frozen bill",
            amount: 42,
            dueDay: 4,
            isPaid: false
        )
        try repository.createPlannedItem(item)

        state.selectedMonth = pastMonth
        try state.refresh()
        let originalPastMonthBalance = state.primaryBankBalance

        state.primaryBankBalance = 999
        state.setPaid(item: item, paid: true)
        state.update(
            item: item,
            label: "Changed",
            amount: 88,
            dueDay: 5,
            dueText: nil,
            type: .credit,
            copiesToNextMonthAutomatically: false,
            notes: "Should not persist"
        )
        state.delete(item: item)
        let created = state.createEntry(type: .fixedDebit, label: "Past add", amount: 11, dueDay: 7)

        let reloaded = try XCTUnwrap(try repository.plannedItems(for: pastMonth).first(where: { $0.id == item.id }))
        XCTAssertEqual(state.primaryBankBalance, originalPastMonthBalance)
        XCTAssertFalse(reloaded.isPaid)
        XCTAssertEqual(reloaded.label, "Frozen bill")
        XCTAssertEqual(reloaded.amount, 42)
        XCTAssertEqual(reloaded.type, .fixedDebit)
        XCTAssertEqual(reloaded.notes, "")
        XCTAssertNil(created)
        XCTAssertEqual(
            try repository.plannedItems(for: pastMonth).filter { $0.label == "Past add" }.count,
            0
        )
    }

    func testUpdatingMonthItemPersistsMatchingStringAndAllowsClearing() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        let account = try XCTUnwrap(try repository.accounts().first)
        let item = PlannedItem(
            accountID: account.id,
            monthKey: state.selectedMonth,
            type: .fixedDebit,
            label: "Council tax",
            amount: 1200,
            dueDay: 10,
            isPaid: false
        )
        try repository.createPlannedItem(item)

        state.update(
            item: item,
            label: "Council tax",
            matchingString: "Statement keywords",
            amount: 1200,
            dueDay: 10,
            dueText: nil,
            type: .fixedDebit,
            copiesToNextMonthAutomatically: true,
            notes: ""
        )

        let savedWithMatchingString = try XCTUnwrap(
            try repository.plannedItems(for: state.selectedMonth).first(where: { $0.id == item.id })
        )
        XCTAssertEqual(savedWithMatchingString.matchingString, "Statement keywords")

        state.update(
            item: item,
            label: "Council tax",
            matchingString: nil,
            amount: 1200,
            dueDay: 10,
            dueText: nil,
            type: .fixedDebit,
            copiesToNextMonthAutomatically: true,
            notes: ""
        )

        let clearedMatchingString = try XCTUnwrap(
            try repository.plannedItems(for: state.selectedMonth).first(where: { $0.id == item.id })
        )
        XCTAssertNil(clearedMatchingString.matchingString)
    }

    func testCreatingMonthItemPersistsMatchingString() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()

        let created = state.createEntry(
            type: .fixedDebit,
            label: "Parking",
            matchingString: "Statement keywords",
            amount: 12,
            dueDay: 4
        )

        let saved = try XCTUnwrap(created)
        XCTAssertEqual(saved.matchingString, "Statement keywords")
        XCTAssertEqual(
            try repository.plannedItems(for: state.selectedMonth).first(where: { $0.id == saved.id })?.matchingString,
            "Statement keywords"
        )
    }

    func testEditingImportedUnplannedItemPromotesSourceToManual() async throws {
        let repository = try makeRepository()
        let state = AppState(repository: repository)

        await state.bootstrapIfNeeded()
        let account = try XCTUnwrap(try repository.accounts().first)
        let item = PlannedItem(
            accountID: account.id,
            monthKey: state.selectedMonth,
            type: .fixedDebit,
            source: .importedUnplanned,
            label: "Shop Purchase",
            amount: 42,
            matchingString: "shop",
            dueDay: 14,
            isPaid: true,
            copiesToNextMonthAutomatically: false,
            notes: "Imported"
        )
        try repository.createPlannedItem(item)

        state.update(
            item: item,
            label: "Shop Purchase",
            matchingString: "shop",
            amount: 42,
            dueDay: 14,
            dueText: nil,
            type: .fixedDebit,
            copiesToNextMonthAutomatically: false,
            notes: "Edited by user"
        )

        let saved = try XCTUnwrap(
            try repository.plannedItems(for: state.selectedMonth).first(where: { $0.id == item.id })
        )
        XCTAssertEqual(saved.source, .manual)
        XCTAssertEqual(saved.matchingString, "shop")
        XCTAssertEqual(saved.notes, "Edited by user")
    }

    func testMonthCalculationEngineDeterministicBudgetAndSuggestedLiving() {
        let budget = MonthCalculationEngine.monthlyBudgetFromWeekModel(
            year: 2026,
            month: 2,
            weeklyEstimate: 100,
            weekendEstimate: 10
        )
        XCTAssertEqual(budget, 480)

        let suggested = MonthCalculationEngine.suggestedLiving(
            projectedNetCredit: 900,
            livingBuffer: 200,
            monthlyBudgetFromWeekModel: 650,
            minSuggestedLiving: 250
        )
        XCTAssertEqual(suggested, 650)

        let minimumSuggested = MonthCalculationEngine.suggestedLiving(
            projectedNetCredit: 300,
            livingBuffer: 200,
            monthlyBudgetFromWeekModel: 120,
            minSuggestedLiving: 250
        )
        XCTAssertEqual(minimumSuggested, 250)
    }

    func testProjectedBalanceMatchesDueTotalsArithmetic() {
        let month = YearMonth(year: 2026, month: 2)
        let accountID = UUID()
        let items = [
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "Rent", amount: 1200, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .transfer, label: "Living expenses", amount: 500, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .credit, label: "Salary", amount: 2000, isPaid: false)
        ]

        let openingBalance: Decimal = 1000
        let totals = MonthCalculationEngine.calculate(
            items: items,
            openingBalance: openingBalance,
            livingBuffer: 100,
            weeklyEstimate: 100,
            weekendEstimate: 10,
            minSuggestedLiving: 250,
            yearMonth: month
        )

        XCTAssertEqual(totals.netOutgoingsDue, -300)
        XCTAssertEqual(totals.projectedBalance, openingBalance - totals.netOutgoingsDue)
        XCTAssertEqual(totals.projectedBalance, 1300)
    }

    func testMonthItemEditorDraftRequiresNameButAllowsZeroAmountToSave() {
        var draft = MonthItemEditorDraft(newType: .fixedDebit, dueDay: 11)

        XCTAssertFalse(draft.canSave)

        draft.label = "Gas bill"
        XCTAssertTrue(draft.canSave)

        draft.amountText = "42.50"
        XCTAssertTrue(draft.canSave)
    }

    func testMonthItemEditorDraftNormalisesNegativeAmountToDebit() {
        var draft = MonthItemEditorDraft(newType: .credit, dueDay: 25)

        draft.amountText = "-1200"
        draft.normalizeAmountInput(locale: Locale(identifier: "en_GB"))

        XCTAssertEqual(draft.entryKind, .debit)
        XCTAssertEqual(draft.amountText, "1200")
    }

    func testMonthItemEditorDraftInitialisesStatementKeywordsFromItem() {
        let draft = MonthItemEditorDraft(
            item: PlannedItem(
                accountID: UUID(),
                monthKey: YearMonth(year: 2026, month: 3),
                type: .fixedDebit,
                label: "Rent",
                amount: 1200,
                matchingString: "monthly rent"
            )
        )

        XCTAssertEqual(draft.matchingString, "monthly rent")
    }

    func testNewPlannedItemsCopyToNextMonthAutomaticallyByDefault() {
        let item = PlannedItem(
            accountID: UUID(),
            monthKey: YearMonth(year: 2026, month: 3),
            type: .fixedDebit,
            label: "Rent",
            amount: 1200
        )

        XCTAssertTrue(item.copiesToNextMonthAutomatically)
        XCTAssertEqual(item.source, .manual)
    }

    func testMonthItemRowMetadataLinesShowDayThenNotes() {
        let item = PlannedItem(
            accountID: UUID(),
            monthKey: YearMonth(year: 2026, month: 3),
            type: .fixedDebit,
            label: "Gas bill",
            amount: 42,
            dueDay: 7,
            dueText: nil,
            isPaid: false,
            notes: "Call to confirm meter reading"
        )

        XCTAssertEqual(
            MonthItemRowContent.metadataLines(for: item),
            ["7th", "Call to confirm meter reading"]
        )
    }

    func testMonthItemRowMetadataLinesHideEmptyNotes() {
        let item = PlannedItem(
            accountID: UUID(),
            monthKey: YearMonth(year: 2026, month: 3),
            type: .credit,
            label: "Salary",
            amount: 1000,
            dueDay: nil,
            dueText: "Floating",
            isPaid: false,
            notes: "   "
        )

        XCTAssertEqual(MonthItemRowContent.metadataLines(for: item), ["Floating"])
    }

    func testMonthItemRowShowsUnplannedIndicatorForImportedUnplannedItems() {
        let outgoingUnplannedItem = PlannedItem(
            accountID: UUID(),
            monthKey: YearMonth(year: 2026, month: 3),
            type: .fixedDebit,
            source: .importedUnplanned,
            label: "Coffee",
            amount: 4.50
        )
        let creditUnplannedItem = PlannedItem(
            accountID: UUID(),
            monthKey: YearMonth(year: 2026, month: 3),
            type: .credit,
            source: .importedUnplanned,
            label: "Refund",
            amount: 12
        )
        let manualItem = PlannedItem(
            accountID: UUID(),
            monthKey: YearMonth(year: 2026, month: 3),
            type: .fixedDebit,
            source: .manual,
            label: "Rent",
            amount: 1200
        )

        XCTAssertEqual(MonthItemRowContent.amountFootnote(for: outgoingUnplannedItem), "unplanned")
        XCTAssertNil(MonthItemRowContent.amountFootnote(for: creditUnplannedItem))
        XCTAssertNil(MonthItemRowContent.amountFootnote(for: manualItem))
    }

    func testMonthItemRowDoesNotHighlightOverdueForZeroAmount() {
        let item = PlannedItem(
            accountID: UUID(),
            monthKey: YearMonth(year: 2026, month: 3),
            type: .fixedDebit,
            label: "Placeholder",
            amount: 0,
            dueDay: 1,
            dueText: nil,
            isPaid: false
        )

        XCTAssertFalse(
            MonthItemRowContent.showsOverdueHighlight(
                for: item,
                isSelectedMonthInPast: false,
                isSelectedMonthInFuture: false,
                todayDay: 12
            )
        )
    }

    func testAutomaticMonthCopySkipsItemsMarkedNotToAutoCopy() {
        let items = [
            PlannedItem(
                accountID: UUID(),
                monthKey: YearMonth(year: 2026, month: 3),
                type: .fixedDebit,
                label: "Rent",
                amount: 1200
            ),
            PlannedItem(
                accountID: UUID(),
                monthKey: YearMonth(year: 2026, month: 3),
                type: .fixedDebit,
                label: "One-off",
                amount: 75,
                copiesToNextMonthAutomatically: false
            )
        ]

        XCTAssertEqual(
            PlannedItem.automaticallyCopiedItems(from: items).map(\.label),
            ["Rent"]
        )
    }

    private func makeRepository() throws -> AccountRepository {
        return AccountRepository(
            privateStore: InMemoryAccountDataStore(),
            sharedStore: InMemoryAccountDataStore()
        )
    }

    private func insertIncomingSharedBudget(into repository: AccountRepository, month: YearMonth) throws {
        let budget = Budget(
            id: UUID(),
            name: "Shared Household",
            ownerParticipantID: "jane",
            sharingState: .shared
        )
        let account = Account(
            id: UUID(),
            budgetID: budget.id,
            name: "Shared Monzo",
            role: .regular,
            type: .current,
            ownerParticipantID: "jane"
        )
        let item = PlannedItem(
            id: UUID(),
            budgetID: budget.id,
            accountID: account.id,
            monthKey: month,
            type: .fixedDebit,
            label: "Shared Rent",
            amount: 1200,
            dueDay: 1,
            isPaid: false
        )
        let wheelOfMoneyItem = WheelOfMoneyItem(
            budgetID: budget.id,
            title: "Shared Christmas",
            amount: 1000,
            month: WheelOfMoneyMonth.december.rawValue,
            isPaid: false,
            notes: "Shared presents"
        )

        try repository.insertShared(
            budget: budget,
            accounts: [account],
            plannedItems: [item],
            transactions: [],
            wheelOfMoneyItems: [wheelOfMoneyItem]
        )
    }

    private static let utcCalendar: Calendar = {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0) ?? .gmt
        return calendar
    }()

    private static func retainHostedTestObject(_ object: AnyObject) {
        retainedHostedTestObjects.append(object)
    }

    private static func makeSchema() -> Schema {
        Schema([
            Budget.self,
            Account.self,
            PlannedItem.self,
            Transaction.self,
            WheelOfMoneyItem.self
        ])
    }

    private static func date(year: Int, month: Int, day: Int) -> Date {
        utcCalendar.date(from: DateComponents(
            calendar: utcCalendar,
            timeZone: utcCalendar.timeZone,
            year: year,
            month: month,
            day: day,
            hour: 12
        ))!
    }

    private func makeTestBudgetShareSession(budgetID: UUID) -> BudgetShareSession {
        let rootRecord = CKRecord(recordType: "Budget")
        let share = CKShare(rootRecord: rootRecord)
        share[CKShare.SystemFieldKey.title] = "MonthlyMoney" as CKRecordValue
        return BudgetShareSession(
            budgetID: budgetID,
            share: share,
            containerIdentifier: MonthlyMoneyPersistenceFactory.cloudKitContainerIdentifier
        )
    }
}

@MainActor
private final class AwaitingAccountDataStoreSpy: AccountDataStore {
    var implementationKind: DataStoreImplementationKind { .inMemory }
    private let backingStore = InMemoryAccountDataStore()
    private(set) var didAwaitInitialCloudImport = false

    func awaitInitialCloudImport(timeout: Duration) async throws {
        _ = timeout
        didAwaitInitialCloudImport = true
    }

    func fetchBudgets() throws -> [Budget] { try backingStore.fetchBudgets() }
    func fetchBudget(id: UUID) throws -> Budget? { try backingStore.fetchBudget(id: id) }
    func upsertBudget(_ budget: Budget) throws { try backingStore.upsertBudget(budget) }
    func deleteBudget(id: UUID) throws { try backingStore.deleteBudget(id: id) }
    func fetchAccounts() throws -> [Account] { try backingStore.fetchAccounts() }
    func fetchAccount(id: UUID) throws -> Account? { try backingStore.fetchAccount(id: id) }
    func upsertAccount(_ account: Account) throws { try backingStore.upsertAccount(account) }
    func deleteAccount(id: UUID) throws { try backingStore.deleteAccount(id: id) }
    func fetchPlannedItems() throws -> [PlannedItem] { try backingStore.fetchPlannedItems() }
    func fetchPlannedItem(id: UUID) throws -> PlannedItem? { try backingStore.fetchPlannedItem(id: id) }
    func fetchPlannedItems(accountIDs: Set<UUID>, monthKey: YearMonth?) throws -> [PlannedItem] {
        try backingStore.fetchPlannedItems(accountIDs: accountIDs, monthKey: monthKey)
    }
    func upsertPlannedItems(_ items: [PlannedItem]) throws { try backingStore.upsertPlannedItems(items) }
    func deletePlannedItem(id: UUID) throws { try backingStore.deletePlannedItem(id: id) }
    func deletePlannedItems(accountID: UUID) throws { try backingStore.deletePlannedItems(accountID: accountID) }
    func fetchTransactions() throws -> [MonthlyMoney.Transaction] { try backingStore.fetchTransactions() }
    func fetchTransactions(accountIDs: Set<UUID>) throws -> [MonthlyMoney.Transaction] {
        try backingStore.fetchTransactions(accountIDs: accountIDs)
    }
    func upsertTransactions(_ transactions: [MonthlyMoney.Transaction]) throws {
        try backingStore.upsertTransactions(transactions)
    }
    func deleteTransactions(accountID: UUID) throws { try backingStore.deleteTransactions(accountID: accountID) }
    func fetchImportedTransactionRecords(accountIDs: Set<UUID>) throws -> [ImportedTransactionRecord] {
        try backingStore.fetchImportedTransactionRecords(accountIDs: accountIDs)
    }
    func upsertImportedTransactionRecords(_ records: [ImportedTransactionRecord]) throws {
        try backingStore.upsertImportedTransactionRecords(records)
    }
    func deleteImportedTransactionRecords(accountID: UUID) throws {
        try backingStore.deleteImportedTransactionRecords(accountID: accountID)
    }
    func fetchWheelOfMoneyItems() throws -> [WheelOfMoneyItem] { try backingStore.fetchWheelOfMoneyItems() }
    func fetchWheelOfMoneyItem(id: UUID) throws -> WheelOfMoneyItem? { try backingStore.fetchWheelOfMoneyItem(id: id) }
    func fetchWheelOfMoneyItems(budgetID: UUID) throws -> [WheelOfMoneyItem] {
        try backingStore.fetchWheelOfMoneyItems(budgetID: budgetID)
    }
    func upsertWheelOfMoneyItems(_ items: [WheelOfMoneyItem]) throws {
        try backingStore.upsertWheelOfMoneyItems(items)
    }
    func deleteWheelOfMoneyItem(id: UUID) throws { try backingStore.deleteWheelOfMoneyItem(id: id) }
    func deleteWheelOfMoneyItems(budgetID: UUID) throws { try backingStore.deleteWheelOfMoneyItems(budgetID: budgetID) }
}
