import Foundation
import XCTest
@testable import MonthlyMoneyCore

final class SharingAndMonthTests: XCTestCase {
    func testLocalBudgetDefaults() {
        let budget = Budget(name: "Home", ownerParticipantID: "owner")
        let account = Account(budgetID: budget.id, name: "Current", role: .regular, type: .current)
        let month = YearMonth(year: 2026, month: 2)
        let item = PlannedItem(
            budgetID: budget.id,
            accountID: account.id,
            monthKey: month,
            type: .fixedDebit,
            label: "Rent",
            amount: 1200
        )
        let transaction = Transaction(budgetID: budget.id, accountID: account.id, monthKey: month, amount: 10)

        XCTAssertEqual(budget.sharingState, .local)
        XCTAssertFalse(budget.usesSeparateAccountForDailyBudget)
        XCTAssertEqual(budget.dailyBudgetAmount, 0)
        XCTAssertEqual(budget.dailyBudgetPaydayDay, 1)
        XCTAssertEqual(account.budgetID, budget.id)
        XCTAssertEqual(item.budgetID, budget.id)
        XCTAssertEqual(transaction.budgetID, budget.id)
    }

    func testPlannedItemMatcherUsesMatchingStringThenFallsBackToLabel() {
        let budget = Budget(name: "Home", ownerParticipantID: "owner")
        let account = Account(budgetID: budget.id, name: "Current", role: .regular, type: .current)
        let month = YearMonth(year: 2026, month: 3)

        let explicitMatch = PlannedItem(
            budgetID: budget.id,
            accountID: account.id,
            monthKey: month,
            type: .fixedDebit,
            label: "Rent",
            amount: 1200,
            matchingString: "Council tax"
        )
        let fallbackMatch = PlannedItem(
            budgetID: budget.id,
            accountID: account.id,
            monthKey: month,
            type: .fixedDebit,
            label: "Rent",
            amount: 1200
        )

        XCTAssertEqual(Self.matchingText(for: explicitMatch), "Council tax")
        XCTAssertEqual(Self.matchingText(for: fallbackMatch), "Rent")
    }

    func testWheelOfMoneyCrudAndPaidToggle() throws {
        let repository = makeRepository()
        let budget = try XCTUnwrap(try repository.localBudget() ?? repository.createBudget(name: "Home", ownerParticipantID: "owner"))
        let item = WheelOfMoneyItem(
            budgetID: budget.id,
            title: "Car insurance",
            amount: 900,
            month: WheelOfMoneyMonth.march.rawValue,
            isPaid: false,
            notes: "Annual policy",
            isAutoGeneratedSavingsEntry: false
        )

        try repository.createWheelOfMoneyItem(item)

        let created = try XCTUnwrap(try repository.wheelOfMoneyItem(id: item.id))
        XCTAssertEqual(created.title, "Car insurance")
        XCTAssertEqual(created.amount, 900)
        XCTAssertEqual(created.month, WheelOfMoneyMonth.march.rawValue)
        XCTAssertFalse(created.isPaid)
        XCTAssertEqual(created.notes, "Annual policy")

        created.title = "Car insurance renewal"
        created.notes = "Updated"
        try repository.saveWheelOfMoneyItem(created)
        try repository.setWheelOfMoneyItemPaid(id: created.id, isPaid: true)

        let updated = try XCTUnwrap(try repository.wheelOfMoneyItem(id: created.id))
        XCTAssertEqual(updated.title, "Car insurance renewal")
        XCTAssertEqual(updated.notes, "Updated")
        XCTAssertTrue(updated.isPaid)

        try repository.deleteWheelOfMoneyItem(id: updated.id)
        XCTAssertNil(try repository.wheelOfMoneyItem(id: updated.id))
        XCTAssertTrue(try repository.wheelOfMoneyItems().isEmpty)
    }

    func testWheelOfMoneyItemsRemainScopedToActiveBudget() throws {
        let privateStore = InMemoryAccountDataStore()
        let sharedStore = InMemoryAccountDataStore()
        let repository = AccountRepository(privateStore: privateStore, sharedStore: sharedStore)

        let localBudget = Budget(name: "Local", ownerParticipantID: "owner", sharingState: .local)
        let sharedBudget = Budget(name: "Shared", ownerParticipantID: "other", sharingState: .shared)
        try privateStore.upsertBudget(localBudget)
        try sharedStore.upsertBudget(sharedBudget)

        try privateStore.upsertWheelOfMoneyItems([
            WheelOfMoneyItem(
                budgetID: localBudget.id,
                title: "Christmas",
                amount: 1000,
                month: WheelOfMoneyMonth.december.rawValue
            )
        ])
        try sharedStore.upsertWheelOfMoneyItems([
            WheelOfMoneyItem(
                budgetID: sharedBudget.id,
                title: "Shared holiday",
                amount: 800,
                month: WheelOfMoneyMonth.august.rawValue
            )
        ])

        XCTAssertEqual(try repository.wheelOfMoneyItems().map(\.title), ["Christmas"])
    }

    func testImportedTransactionRecordsRemainScopedToOwningAccounts() throws {
        let privateStore = InMemoryAccountDataStore()
        let sharedStore = InMemoryAccountDataStore()
        let repository = AccountRepository(privateStore: privateStore, sharedStore: sharedStore)

        let privateBudget = Budget(name: "Private", ownerParticipantID: "owner", sharingState: .local)
        let sharedBudget = Budget(name: "Shared", ownerParticipantID: "other", sharingState: .shared)
        try privateStore.upsertBudget(privateBudget)
        try sharedStore.upsertBudget(sharedBudget)

        let privateAccount = Account(budgetID: privateBudget.id, name: "Private account", role: .regular, type: .current)
        let sharedAccount = Account(budgetID: sharedBudget.id, name: "Shared account", role: .regular, type: .current)
        try privateStore.upsertAccount(privateAccount)
        try sharedStore.upsertAccount(sharedAccount)

        let privateRecord = ImportedTransactionRecord(
            budgetID: privateBudget.id,
            accountID: privateAccount.id,
            sourceKind: "nationwide_ofx",
            sourceAccountIdentifier: "****1111",
            externalTransactionID: "FITID-PRIVATE",
            postedAt: Date(timeIntervalSince1970: 1_000),
            amount: -12.34,
            payee: "Private shop",
            transactionType: "POS",
            rawSourcePayload: "{\"fitid\":\"FITID-PRIVATE\"}",
            importedAt: Date(timeIntervalSince1970: 1_100)
        )
        let sharedRecord = ImportedTransactionRecord(
            budgetID: sharedBudget.id,
            accountID: sharedAccount.id,
            sourceKind: "nationwide_ofx",
            sourceAccountIdentifier: "****2222",
            externalTransactionID: "FITID-SHARED",
            postedAt: Date(timeIntervalSince1970: 2_000),
            amount: 45.67,
            payee: "Shared shop",
            transactionType: "CREDIT",
            rawSourcePayload: "{\"fitid\":\"FITID-SHARED\"}",
            importedAt: Date(timeIntervalSince1970: 2_100)
        )

        try repository.createImportedTransactionRecord(privateRecord)
        try repository.createImportedTransactionRecord(sharedRecord)

        XCTAssertEqual(
            try repository.importedTransactionRecords(accountIDs: [privateAccount.id]).map(\.externalTransactionID),
            ["FITID-PRIVATE"]
        )
        XCTAssertEqual(
            try repository.importedTransactionRecords(accountIDs: [sharedAccount.id]).map(\.externalTransactionID),
            ["FITID-SHARED"]
        )
    }

    func testImportedTransactionRecordsDeduplicateAcrossStoresByRecordID() throws {
        let privateStore = InMemoryAccountDataStore()
        let sharedStore = InMemoryAccountDataStore()
        let repository = AccountRepository(privateStore: privateStore, sharedStore: sharedStore)

        let sharedRecordID = UUID()
        let accountID = UUID()
        let privateRecord = ImportedTransactionRecord(
            id: sharedRecordID,
            budgetID: UUID(),
            accountID: accountID,
            sourceKind: "nationwide_ofx",
            sourceAccountIdentifier: "****1111",
            externalTransactionID: "FITID-DUPLICATE",
            postedAt: Date(timeIntervalSince1970: 1_000),
            amount: -12.34,
            payee: "Private copy",
            transactionType: "POS",
            rawSourcePayload: "{\"fitid\":\"FITID-DUPLICATE\"}"
        )
        let sharedRecord = ImportedTransactionRecord(
            id: sharedRecordID,
            budgetID: UUID(),
            accountID: accountID,
            sourceKind: "nationwide_ofx",
            sourceAccountIdentifier: "****1111",
            externalTransactionID: "FITID-DUPLICATE",
            postedAt: Date(timeIntervalSince1970: 1_000),
            amount: -12.34,
            payee: "Shared copy",
            transactionType: "POS",
            rawSourcePayload: "{\"fitid\":\"FITID-DUPLICATE\"}"
        )

        try privateStore.upsertImportedTransactionRecords([privateRecord])
        try sharedStore.upsertImportedTransactionRecords([sharedRecord])

        let fetched = try repository.importedTransactionRecords(accountIDs: [accountID])
        XCTAssertEqual(fetched.count, 1)
        XCTAssertEqual(fetched.first?.id, sharedRecordID)
    }

    func testNewAccountsAttachToActiveLocalBudget() throws {
        let repository = makeRepository()
        let account = try repository.createAccount(name: "Current", role: .regular, type: .current, ownerParticipantID: "owner")
        XCTAssertEqual(account.budgetID, try repository.activeBudget()?.id)
        XCTAssertEqual(try repository.activeBudget()?.sharingState, .local)
    }

    func testShareBudgetMarksPrivateBudgetSharedAndPreservesTotals() throws {
        let privateStore = InMemoryAccountDataStore()
        let sharedStore = InMemoryAccountDataStore()
        let repository = AccountRepository(privateStore: privateStore, sharedStore: sharedStore)
        let account = try repository.createAccount(name: "Bills", role: .regular, type: .current, ownerParticipantID: "owner")
        let month = YearMonth(year: 2026, month: 2)
        try repository.createPlannedItem(PlannedItem(accountID: account.id, monthKey: month, type: .fixedDebit, label: "Rent", amount: 1200))
        try repository.createPlannedItem(PlannedItem(accountID: account.id, monthKey: month, type: .credit, label: "Salary", amount: 2500))
        try repository.createTransaction(Transaction(accountID: account.id, monthKey: month, amount: 100, note: "Stub"))
        try repository.createWheelOfMoneyItem(
            WheelOfMoneyItem(
                budgetID: account.budgetID,
                title: "Christmas",
                amount: 1000,
                month: WheelOfMoneyMonth.december.rawValue,
                notes: "Presents"
            )
        )

        let before = try repository.plannedItems(for: month)
        let beforeTotals = MonthCalculationEngine.calculate(items: before, openingBalance: 1000, livingBuffer: 100, weeklyEstimate: 100, weekendEstimate: 10, minSuggestedLiving: 1500, yearMonth: month)

        let service = BudgetSharingService(repository: repository)
        let sharedBudget = try service.shareBudget(participantsSelection: ["p2"])

        XCTAssertEqual(sharedBudget.sharingState, .shared)
        XCTAssertEqual(try repository.activeBudget()?.id, sharedBudget.id)
        XCTAssertEqual(try privateStore.fetchBudgets().map(\.id), [sharedBudget.id])
        XCTAssertEqual(try privateStore.fetchBudgets().first?.sharingState, .shared)
        XCTAssertEqual(try privateStore.fetchAccounts().map(\.id), [account.id])
        XCTAssertEqual(try privateStore.fetchPlannedItems(accountIDs: [account.id], monthKey: month).count, 2)
        XCTAssertEqual(try privateStore.fetchTransactions(accountIDs: [account.id]).count, 1)
        XCTAssertEqual(try privateStore.fetchWheelOfMoneyItems().map(\.title), ["Christmas"])
        XCTAssertTrue(try sharedStore.fetchBudgets().isEmpty)
        XCTAssertTrue(try sharedStore.fetchAccounts().isEmpty)
        XCTAssertTrue(try sharedStore.fetchPlannedItems(accountIDs: [account.id], monthKey: nil).isEmpty)
        XCTAssertTrue(try sharedStore.fetchTransactions(accountIDs: [account.id]).isEmpty)
        XCTAssertTrue(try sharedStore.fetchWheelOfMoneyItems().isEmpty)

        let after = try repository.plannedItems(for: month)
        let afterTotals = MonthCalculationEngine.calculate(items: after, openingBalance: 1000, livingBuffer: 100, weeklyEstimate: 100, weekendEstimate: 10, minSuggestedLiving: 1500, yearMonth: month)
        XCTAssertEqual(beforeTotals, afterTotals)
        XCTAssertEqual(try repository.wheelOfMoneyItems().map(\.title), ["Christmas"])
    }

    func testActiveBudgetScope() throws {
        let privateStore = InMemoryAccountDataStore()
        let sharedStore = InMemoryAccountDataStore()

        let localBudget = Budget(name: "Local", ownerParticipantID: "owner", sharingState: .local)
        let sharedBudget = Budget(name: "Shared", ownerParticipantID: "owner", sharingState: .shared)
        try privateStore.upsertBudget(localBudget)
        try sharedStore.upsertBudget(sharedBudget)

        let localAccount = Account(budgetID: localBudget.id, name: "Current", role: .regular, type: .current)
        let sharedAccount = Account(budgetID: sharedBudget.id, name: "Joint", role: .regular, type: .current)
        try privateStore.upsertAccount(localAccount)
        try sharedStore.upsertAccount(sharedAccount)

        let month = YearMonth(year: 2026, month: 2)
        try privateStore.upsertPlannedItems([
            PlannedItem(budgetID: localBudget.id, accountID: localAccount.id, monthKey: month, type: .fixedDebit, label: "Rent", amount: 1200)
        ])
        try sharedStore.upsertPlannedItems([
            PlannedItem(budgetID: sharedBudget.id, accountID: sharedAccount.id, monthKey: month, type: .fixedDebit, label: "Shared Rent", amount: 800)
        ])

        let repository = AccountRepository(privateStore: privateStore, sharedStore: sharedStore)

        XCTAssertEqual(try repository.activeBudget()?.id, localBudget.id)
        XCTAssertEqual(try repository.accounts().map(\.id), [localAccount.id])
        XCTAssertEqual(try repository.plannedItems(for: month).map(\.accountID), [localAccount.id])
    }

    func testActiveBudgetPrefersMostRecentlyUpdatedLocalBudget() throws {
        let privateStore = InMemoryAccountDataStore()
        let repository = AccountRepository(
            privateStore: privateStore,
            sharedStore: InMemoryAccountDataStore()
        )
        let older = Budget(
            id: UUID(),
            name: "Older",
            ownerParticipantID: "owner",
            sharingState: .local,
            createdAt: Date(timeIntervalSince1970: 100),
            updatedAt: Date(timeIntervalSince1970: 200)
        )
        let newer = Budget(
            id: UUID(),
            name: "Newer",
            ownerParticipantID: "owner",
            sharingState: .local,
            createdAt: Date(timeIntervalSince1970: 100),
            updatedAt: Date(timeIntervalSince1970: 300)
        )

        try privateStore.upsertBudget(older)
        try privateStore.upsertBudget(newer)

        XCTAssertEqual(try repository.activeBudget()?.id, newer.id)
        XCTAssertEqual(try repository.localBudget()?.id, newer.id)
    }

    func testCreatingPlannedItemTouchesOwningBudgetUpdatedAt() throws {
        let privateStore = InMemoryAccountDataStore()
        let repository = AccountRepository(
            privateStore: privateStore,
            sharedStore: InMemoryAccountDataStore()
        )
        let originalUpdatedAt = Date(timeIntervalSince1970: 100)
        let budget = Budget(
            id: UUID(),
            name: "Budget",
            ownerParticipantID: "owner",
            sharingState: .local,
            createdAt: Date(timeIntervalSince1970: 50),
            updatedAt: originalUpdatedAt
        )
        let account = Account(
            id: UUID(),
            budgetID: budget.id,
            name: "Main",
            role: .regular,
            type: .current,
            ownerParticipantID: "owner"
        )

        try privateStore.upsertBudget(budget)
        try privateStore.upsertAccount(account)
        try repository.createPlannedItem(
            PlannedItem(
                accountID: account.id,
                monthKey: YearMonth(year: 2026, month: 3),
                type: .fixedDebit,
                label: "Rent",
                amount: 1000
            )
        )

        let savedBudget = try XCTUnwrap(privateStore.fetchBudget(id: budget.id))
        XCTAssertGreaterThan(savedBudget.updatedAt, originalUpdatedAt)
    }

    func testReconcileDuplicateLocalBudgetsKeepsNewestAndDeletesOlderDependents() throws {
        let privateStore = InMemoryAccountDataStore()
        let repository = AccountRepository(
            privateStore: privateStore,
            sharedStore: InMemoryAccountDataStore()
        )

        let olderBudget = Budget(
            id: UUID(),
            name: "Older",
            ownerParticipantID: "owner",
            sharingState: .local,
            createdAt: Date(timeIntervalSince1970: 100),
            updatedAt: Date(timeIntervalSince1970: 200)
        )
        let newerBudget = Budget(
            id: UUID(),
            name: "Newer",
            ownerParticipantID: "owner",
            sharingState: .local,
            createdAt: Date(timeIntervalSince1970: 100),
            updatedAt: Date(timeIntervalSince1970: 300)
        )
        let olderAccount = Account(
            id: UUID(),
            budgetID: olderBudget.id,
            name: "Old Current",
            role: .regular,
            type: .current,
            ownerParticipantID: "owner"
        )
        let newerAccount = Account(
            id: UUID(),
            budgetID: newerBudget.id,
            name: "New Current",
            role: .regular,
            type: .current,
            ownerParticipantID: "owner"
        )

        try privateStore.upsertBudget(olderBudget)
        try privateStore.upsertBudget(newerBudget)
        try privateStore.upsertAccount(olderAccount)
        try privateStore.upsertAccount(newerAccount)
        try privateStore.upsertPlannedItems([
            PlannedItem(
                id: UUID(),
                budgetID: olderBudget.id,
                accountID: olderAccount.id,
                monthKey: YearMonth(year: 2026, month: 3),
                type: .fixedDebit,
                label: "Old Rent",
                amount: 100
            ),
            PlannedItem(
                id: UUID(),
                budgetID: newerBudget.id,
                accountID: newerAccount.id,
                monthKey: YearMonth(year: 2026, month: 3),
                type: .fixedDebit,
                label: "New Rent",
                amount: 200
            )
        ])
        try privateStore.upsertTransactions([
            Transaction(
                id: UUID(),
                budgetID: olderBudget.id,
                accountID: olderAccount.id,
                monthKey: YearMonth(year: 2026, month: 3),
                amount: 10
            ),
            Transaction(
                id: UUID(),
                budgetID: newerBudget.id,
                accountID: newerAccount.id,
                monthKey: YearMonth(year: 2026, month: 3),
                amount: 20
            )
        ])

        let removed = try repository.reconcileDuplicateLocalBudgets()

        XCTAssertEqual(removed, 1)
        XCTAssertEqual(try repository.localBudget()?.id, newerBudget.id)
        XCTAssertEqual(try privateStore.fetchBudgets().map(\.id), [newerBudget.id])
        XCTAssertEqual(try privateStore.fetchAccounts().map(\.id), [newerAccount.id])
        XCTAssertEqual(
            try privateStore.fetchPlannedItems(accountIDs: [newerAccount.id], monthKey: nil).map(\.label),
            ["New Rent"]
        )
        XCTAssertEqual(
            try privateStore.fetchTransactions(accountIDs: [newerAccount.id]).map(\.amount),
            [20]
        )
    }

    func testShareBudgetRejectsAlreadySharedBudget() throws {
        let repository = makeRepository()
        _ = try repository.createAccount(name: "Current", role: .regular, type: .current, ownerParticipantID: "owner")

        let service = BudgetSharingService(repository: repository)
        _ = try service.shareBudget(participantsSelection: [])

        let sharedBudget = try service.shareBudget(participantsSelection: [])
        XCTAssertEqual(sharedBudget.sharingState, .shared)
        XCTAssertEqual(try repository.localBudget()?.id, sharedBudget.id)
    }

    func testMonthCalculationDeterministicBudgetAndSuggestedLiving() {
        XCTAssertEqual(
            MonthCalculationEngine.monthlyBudgetFromWeekModel(year: 2026, month: 2, weeklyEstimate: 100, weekendEstimate: 10),
            480
        )
        XCTAssertEqual(
            MonthCalculationEngine.suggestedLiving(projectedNetCredit: 900, livingBuffer: 200, monthlyBudgetFromWeekModel: 650, minSuggestedLiving: 250),
            650
        )
    }

    func testProjectedBalanceMatchesDueTotalsArithmetic() {
        let month = YearMonth(year: 2026, month: 2)
        let accountID = UUID()
        let items = [
            PlannedItem(accountID: accountID, monthKey: month, type: .fixedDebit, label: "Rent", amount: 1200, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .transfer, label: "Living expenses", amount: 500, isPaid: false),
            PlannedItem(accountID: accountID, monthKey: month, type: .credit, label: "Salary", amount: 2000, isPaid: false)
        ]

        let openingBalance: Decimal = 1000
        let totals = MonthCalculationEngine.calculate(
            items: items,
            openingBalance: openingBalance,
            livingBuffer: 100,
            weeklyEstimate: 100,
            weekendEstimate: 10,
            minSuggestedLiving: 250,
            yearMonth: month
        )

        XCTAssertEqual(totals.netOutgoingsDue, -300)
        XCTAssertEqual(totals.projectedBalance, openingBalance - totals.netOutgoingsDue)
        XCTAssertEqual(totals.projectedBalance, 1300)
    }

    func testDeletingCurrentMonthItemDoesNotDeleteMatchingItemInNextMonth() throws {
        let repository = makeRepository()
        let account = try repository.createAccount(name: "Bills", role: .regular, type: .current, ownerParticipantID: "owner")
        let current = YearMonth(year: 2026, month: 3)
        let next = YearMonth(year: 2026, month: 4)

        let currentItem = PlannedItem(
            accountID: account.id,
            monthKey: current,
            type: .fixedDebit,
            label: "Rent",
            amount: 1200,
            dueDay: 1,
            isPaid: false
        )
        let nextItem = PlannedItem(
            accountID: account.id,
            monthKey: next,
            type: .fixedDebit,
            label: "Rent",
            amount: 1200,
            dueDay: 1,
            isPaid: false
        )

        try repository.createPlannedItem(currentItem)
        try repository.createPlannedItem(nextItem)
        try repository.deletePlannedItem(id: currentItem.id)

        let currentItems = try repository.plannedItems(for: current)
        let nextItems = try repository.plannedItems(for: next)

        XCTAssertFalse(currentItems.contains(where: { $0.id == currentItem.id }))
        XCTAssertTrue(nextItems.contains(where: { $0.id == nextItem.id }))
    }

    func testAutomaticMonthCopySkipsItemsMarkedNotToAutoCopy() {
        let items = [
            PlannedItem(
                accountID: UUID(),
                monthKey: YearMonth(year: 2026, month: 3),
                type: .fixedDebit,
                label: "Rent",
                amount: 1200
            ),
            PlannedItem(
                accountID: UUID(),
                monthKey: YearMonth(year: 2026, month: 3),
                type: .fixedDebit,
                label: "One-off",
                amount: 75,
                copiesToNextMonthAutomatically: false
            )
        ]

        XCTAssertEqual(
            PlannedItem.automaticallyCopiedItems(from: items).map(\.label),
            ["Rent"]
        )
    }

    private func makeRepository() -> AccountRepository {
        AccountRepository(
            privateStore: InMemoryAccountDataStore(),
            sharedStore: InMemoryAccountDataStore()
        )
    }

    private static func matchingText(for item: PlannedItem) -> String {
        let trimmed = item.matchingString?.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines) ?? ""
        return trimmed.isEmpty ? item.label : trimmed
    }
}
